dashborad/urls.py
from django.conf.urls import url, include
from . import views
from . import user, server, k8s
from dashborad.user import group
from dashborad.k8s import deletes
urlpatterns = [
    # url(r'^login/', views.login_view),
    url(r'^login/', views.Log_In_Out.as_view()),
    url(r'^logout/', views.LogOut.as_view()),
    url(r'^$', views.IndexView.as_view()),
    # url(r'^user/userlist/', user.UserListView.as_view()),
    url(r'^user/userlist/', user.LW.as_view()),
    url(r'^user/modify/', user.Modify_status.as_view()),
    url(r'^user/modp/', user.ModifyDepartmentView.as_view()),
    url(r'^user/mp', user.ModifyPhoneView.as_view()),
    url(r'^permissions/', include([
        url(r'^none/$', views.permit),
    ])),
    url(r'^group/', include([
        url(r'list/$', group.GroupListView.as_view()),
        url(r'^$', group.GroupView.as_view()),
        url(r'^usergroup/', group.UserGroup.as_view()),
        url(r'^per/', group.PermissionList.as_view()),

    ])),
    url(r'^server/', include([
        url(r'^list/$', server.GroupList.as_view()),
        url(r'add_server', server.AddServer.as_view())
    ])),
    url(r'^k8s/', include([
        url(r'^podlist/$', k8s.pod_list),
        url(r'^nmlist/$', k8s.Nm_list.as_view()),
        url(r'^delete/ns/(?P<ns>.*)/$', deletes.delete_ns, name='delete'),
        url(r'^dp/$', k8s.Dp_list.as_view(), name='test'),
        url(r'^dp/(?P<types>.*)$', k8s.Add_Mod_Dp.as_view(), name='test'),
        url(r'^select/(?P<types>.*)', k8s.SelectType.as_view(), name='ls_ns')
    ]))
]

k8s_ui/dashborad/urls.py
from django.conf.urls import url, include
from . import views
from . import user, server, k8s
from dashborad.user import group
from dashborad.k8s import deletes
urlpatterns = [
    # url(r'^login/', views.login_view),
    url(r'^login/', views.Log_In_Out.as_view()),
    url(r'^logout/', views.LogOut.as_view()),
    url(r'^$', views.IndexView.as_view()),
    # url(r'^user/userlist/', user.UserListView.as_view()),
    url(r'^user/userlist/', user.LW.as_view()),
    url(r'^user/modify/', user.Modify_status.as_view()),
    url(r'^user/modp/', user.ModifyDepartmentView.as_view()),
    url(r'^user/mp', user.ModifyPhoneView.as_view()),
    url(r'^permissions/', include([
        url(r'^none/$', views.permit),
    ])),
    url(r'^group/', include([
        url(r'list/$', group.GroupListView.as_view()),
        url(r'^$', group.GroupView.as_view()),
        url(r'^usergroup/', group.UserGroup.as_view()),
        url(r'^per/', group.PermissionList.as_view()),

    ])),
    url(r'^server/', include([
        url(r'^list/$', server.GroupList.as_view()),
        url(r'add_server', server.AddServer.as_view())
    ])),
    url(r'^k8s/', include([
        url(r'^podlist/$', k8s.pod_list),
        url(r'^nmlist/$', k8s.Nm_list.as_view()),
        url(r'^delete/ns/(?P<ns>.*)/$', deletes.delete_ns, name='delete'),
        url(r'^dp/$', k8s.Dp_list.as_view(), name='test'),
        url(r'^dp/(?P<types>.*)$', k8s.Add_Mod_Dp.as_view(), name='test'),
        url(r'^select/(?P<types>.*)', k8s.SelectType.as_view(), name='ls_ns')
    ]))
]

k8s_ui/opsweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include("dashborad.urls")),
]

kubeweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

dashborad/models.py
# coding:utf8
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Server(models.Model):
    hostname = models.CharField(max_length=32, unique=True)
    ip = models.CharField(max_length=15, unique=True)
    cpu = models.CharField(max_length=50, null=True)
    mem = models.CharField(max_length=50)
    disk = models.CharField(max_length=50)
    status = models.IntegerField()
    loads = models.CharField(max_length=20)

    class Meta:
        db_table = 'server'
        # permissions = (
        #     ('view_server', 'view servers info'),   # 添加一个权限到数据库中的auth_permission表中
        #     # 添加权限
        #     #  user.user_permissions.add(权限对象)
        #     # 权限对象  Permission.objects.get(pk=28)
        #     # 权限列表  Permission.objects.filter(pk=28)
        #     # 清空权限 user.user_permissions = []
        #     # 检查用户是否拥有权限 has_perm来检查用户使用有权限
        #     # 检查用户是否拥有权限 has_perm来检查用户使用有权限
        # # )
        # permissions = (
        #     ('view_server', '访问服务器信息'),
        #     ('view_user_list', '访问用户列表')

        # 授权
        # from django.contrib.auth.models import Permission, ContentType
        # Permission()
        # p
        # .name = '访问用户列表'
        #
        # p.content_type = ct
        #
        # p.codename = 'view_user_list'
        #
        # p.save()


# class Crontab(models.Model):
#     details = models.CharField(max_length=256)
#     host = models.ForeignKey(Server, null=False)


class test(models.Model):
    a = models.CharField(max_length=21)
    on_delete = models.DO_NOTHING,


class IDC(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        db_table = 'idc'


class Department(models.Model):
    name = models.CharField(max_length=11, null=True)
    objects = models.Manager()  # 引用的时候发现没有这个属性,临时添加的.

    class Meta:
        db_table = 'department'


class Profile(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=11)
    department = models.CharField(max_length=32)
    title = models.CharField(max_length=32)
    department = models.ForeignKey(Department, null=True)
    objects = models.Manager()  # 引用的时候发现没有这个属性,临时添加的.


    class Meta:
        db_table = 'user_profile'
        default_related_name = 'profile'
# # 一个一对一的例子
    # user = models.OneToOneField(User) 关联一对一关联
    #
    # user = User.objects.create_user('rock11', 'rock@51@.com', '123')
    # user_profile = Profile
    #
    # user_profile.user = user
    # user_profile.phone = '123'
    # user_profile.title = '云维'
    # user_profile.save()
    # 查询
    #
    # user = User.objects.get(username='rock')
    # user.profile.title


    # 同步数据
    # python manage.py makemigrations dashborad
    # python manage.py migrate dashborad
    # python manage.py shell
    # 如果出错,
        # python manage.py makemigrations dashborad --fake  让这个步骤强行成功


    # 添加数据
    #   from dashborad.models import Department
    #   d = Department(name='devops')
    #   d.save()

    # 或者 Department.objects.create(name='dev'), 添加一个一个开发部.




    #     from django.db import models
    #
    #     class Place(models.Model):
    #         name = models.CharField(max_length=50)
    #         address = models.CharField(max_length=80)
    #
    #         def __str__(self):  # __unicode__ on Python 2
    #             return "%s the place" % self.name
    #
    #     class Restaurant(models.Model):
    #         place = models.OneToOneField(Place, primary_key=True)
    #         serves_hot_dogs = models.BooleanField(default=False)
    #         serves_pizza = models.BooleanField(default=False)
    #
    #         def __str__(self):  # __unicode__ on Python 2
    #             return "%s the restaurant" % self.place.name
    #
    #     class Waiter(models.Model):
    #         restaurant = models.ForeignKey(Restaurant)
    #         name = models.CharField(max_length=50)
    #
    #         def __str__(self):  # __unicode__ on Python 2
    #             return "%s the waiter at %s" % (self.name, self.restaurant)
    #
    #     以下是可以使用Python
    #     API执行查询操作的示例。
    #
    #     创建几个Places对象：
    #
    #     >> > p1 = Place(name='Demon Dogs', address='944 W. Fullerton')
    #     >> > p1.save()
    #     >> > p2 = Place(name='Ace Hardware', address='1013 N. Ashland')
    #     >> > p2.save()
    #     创建Restaurant对象。将“父”对象的ID作为此对象的ID：
    #
    #     >> > r = Restaurant(place=p1, serves_hot_dogs=True, serves_pizza=False)
    #     >> > r.save()
    #     从Restaurant对象可以访问它的Place：
    #
    #     >> > r.place
    #     < Place: Demon
    #     Dogs
    #     the
    #     place >
    #     从Place对象可以访问它的Restaurant(如果存在的话)：
    #
    #     >> > p1.restaurant
    #     < Restaurant: Demon
    #     Dogs
    #     the
    #     restaurant >
    #     p2没有相关的餐厅：
    #
    #     >> > from django.core.exceptions import ObjectDoesNotExist
    #     >> > try:
    #         >> > p2.restaurant
    #     >> > except ObjectDoesNotExist:
    #     >> > print("There is no restaurant here.")
    #     There is no
    #     restaurant
    #     here.
    #     您还可以使用hasattr来避免异常捕获的需要：
    #
    #     >> > hasattr(p2, 'restaurant')
    #     False
    #     使用赋值表示Place。由于place字段是Restaurant表的主键, 所以这里的save()
    #     操作会创建一个新的Restaurant对象：
    #
    #     >> > r.place = p2
    #     >> > r.save()
    #     >> > p2.restaurant
    #     < Restaurant: Ace
    #     Hardware
    #     the
    #     restaurant >
    #     >> > r.place
    #     < Place: Ace
    #     Hardware
    #     the
    #     place >
    #     再次指定Place，这次使用相反的方向进行赋值：
    #
    #     >> > p1.restaurant = r
    #     >> > p1.restaurant
    #     < Restaurant: Demon
    #     Dogs
    #     the
    #     restaurant >
    #     请注意，必须先保存对象，然后才能将其分配给一对一关系。例如，使用未保存的Place创建Restaurant会产生ValueError：
    #
    #     >> > p3 = Place(name='Demon Dogs', address='944 W. Fullerton')
    #     >> > Restaurant(place=p3, serves_hot_dogs=True, serves_pizza=False)
    #     Traceback(most
    #     recent
    #     call
    #     last):
    #     ...
    #     ValueError: 'Cannot assign "<Place: Demon Dogs>": "Place" instance isn'
    #     t
    #     saved in the
    #     database.
    #     '
    #     >> > p.restaurant = Restaurant(place=p, serves_hot_dogs=True, serves_pizza=False)
    #     Traceback(most
    #     recent
    #     call
    #     last):
    #     ...
    #     ValueError: 'Cannot assign "<Restaurant: Demon Dogs the restaurant>": "Restaurant" instance isn'
    #     t
    #     saved in the
    #     database.

dashborad/views.py
# coding:utf8
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, QueryDict
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
import logging
from django.contrib.auth.decorators import permission_required, login_required
from django.utils.decorators import method_decorator
from django.conf import settings
logger = logging.getLogger('opsweb')
# Create your views here.


class Log_In_Out(View):

    def get(self, request):
        return render(request, 'login.html', {'title': 'rebbot 晕为'})

    def post(self, request):
            username = request.POST.get('username', None)
            password = request.POST.get('password', None)
            ret = {'status': 0}
            # 验证用户名密码
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    ret['nexturl'] = '/'
                else:
                    ret['status'] = 1
                    ret['errmsg'] = '用户被禁用'

            else:
                ret['status'] = 2
                ret['errmsg'] = 'err'
                print ret
            return JsonResponse(ret, safe=True)


class LogOut(View):
    @method_decorator(login_required)
    def get(self, request):
        logout(request)
        return HttpResponse('用户退出chenggong')


class IndexView(View):
    @method_decorator(login_required)
    # @method_decorator(permission_required('dashborad.view_server', login_url='/permissions/none'))
    def get(self, request):
        # if request.user.has_perm('dashborad.view_server'):
        #     logger.debug('有权限')
        # else:
        #     logger.error('无权限')


        # logging.debug('tessdfsdf')
        # logger = logging.getLogger('opsweb')
        # logger.error('index err')
        return render(request, "public/index.html")


@login_required
def permit(request):
    return render(request, "public/pr.html")

k8s_ui/dashborad/views.py
# coding:utf8
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, QueryDict
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
import logging
from django.contrib.auth.decorators import permission_required, login_required
from django.utils.decorators import method_decorator
from django.conf import settings
logger = logging.getLogger('opsweb')
# Create your views here.


class Log_In_Out(View):

    def get(self, request):
        return render(request, 'login.html', {'title': 'rebbot 晕为'})

    def post(self, request):
            username = request.POST.get('username', None)
            password = request.POST.get('password', None)
            ret = {'status': 0}
            # 验证用户名密码
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    ret['nexturl'] = '/'
                else:
                    ret['status'] = 1
                    ret['errmsg'] = '用户被禁用'

            else:
                ret['status'] = 2
                ret['errmsg'] = 'err'
                print ret
            return JsonResponse(ret, safe=True)


class LogOut(View):
    @method_decorator(login_required)
    def get(self, request):
        logout(request)
        return HttpResponse('用户退出chenggong')


class IndexView(View):
    @method_decorator(login_required)
    # @method_decorator(permission_required('dashborad.view_server', login_url='/permissions/none'))
    def get(self, request):
        # if request.user.has_perm('dashborad.view_server'):
        #     logger.debug('有权限')
        # else:
        #     logger.error('无权限')


        # logging.debug('tessdfsdf')
        # logger = logging.getLogger('opsweb')
        # logger.error('index err')
        return render(request, "public/index.html")


@login_required
def permit(request):
    return render(request, "public/pr.html")

dashborad/templates/user/department.html
{% extends "public/layout.html" %}

{% block body %}
<form class="form-horizontal" method="post">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-3">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email" value="{{ user_obj.email }}" disabled>
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">部门</label>
    <div class="col-sm-3" name="test", value="ccccccc">
      <select class="form-control" name="department">
        <!--写了name 才有返回值-->
          <option value="0">请选择部门</option>
          {% for i in departments %}
            print (i)
            <option value= {{ i.id }} {% if i.id == user_obj.profile.department.id %}selected {% endif %}>{{ i.name }}</option>
          {% endfor %}ß
      </select>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <input type="hidden" name="user" value={{ user_obj.id }}>
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>
{% endblock %}

{% block js %}
    <script>
        console.log("index view")
    </script>
{% endblock %}

dashborad/templates/user/group_permission_list.html
{% extends "public/layout.html" %}

{% block body %}
<d1 class="dl-horizontal">
    <form action="" method="post" role="form" class="form-horizontal">
    {% for i in content_type %}
        <dt>{{ i.app_label }}---{{ i.model }}:</dt>
            <dd>
                <ul>
                    {% for j in i.permission_set.all %}
                    <li>
                        <input type="checkbox" name="permission" value="{{ j.id }}" {% if j.id in group_permissions %}checked{% endif %}>
                        <lable>{{ j.name }}</lable>
                    </li>
                    {% endfor %}
                </ul>
            </dd>
    {% endfor %}
        <div>
    <input type="hidden" name="group" value="{{ group }}">
    <input type="submit" class="btn btn-primary" value="修改">
    <input type="reset" class="btn warning" value="取消">

</div>
    </form>
</d1>

{% endblock %}

dashborad/templates/user/mp.html
{% extends "public/layout.html" %}

{% block body %}
<form class="form-horizontal" method="post">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-3">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email" value="{{ user_obj.email }}" disabled>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">手机号</label>
    <div class="col-sm-3">
      <input type="hidden" name="user_id" value={{ user_obj.id }}>
      <input  class="form-control" id="inputEmail3" placeholder="phone" name='pnum'">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <input type="hidden" name="user" value={{ user_obj.id }}>
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>
{% endblock %}

{% block js %}
    <script>
        console.log("index view")
    </script>
{% endblock %}

dashborad/templates/user/userlist.html
{% extends "public/layout.html" %}

{% block body %}
     <table class="table table-hover">
         <tr>
             <th>#</th>
             <th>用户</th>
             <th>email</th>

             <th>操作</th>
         </tr>
         {% for user in userlist %}
         <tr>
             <td>{{ forloop.counter }}</td>
             <td>{{ user.username }}</td>
             <td>{{ user.email }}</td>
             <td>
                 <div class="btn-group">
                     <div class = 'btn-group'>
                         <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id = 'dropdownMenu1'
                                 data-toggle="dropdown" aria-expanded="false">
                         修改
                         <span class="caret"></span>
                             </button>
                             <ul class = 'dropdown-menu' role="menu" aria-labelledby="dropdownMenu1">
                             <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>
                             <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another action</a></li>
                             <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Something else here </a></li>
                             <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>

                         </ul>
                     </div>
                     <button class='btn btn-sm btn-warning  modify_user_status' status = 'true' data='1'> 禁用 </button>
                 </div>
             </td>
              <td>
                <div class="btn-group">
                    <div class="btn-group">
                        <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="false">
                            修改
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another action</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Something else here</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>
                        </ul>
                    </div>
                    {% if user.is_active %}
                        <button type="button" class="btn btn-sm btn-warning modify_user_status" status="true" data="{{ user.id }}">禁用</button>
                    {% else %}
                        <button type="button" class="btn btn-sm modify_user_status btn-info" status="false" data="{{ user.id }}">开启</button>
                    {% endif %}
                </div>
            </td>

         </tr>
         {% endfor %}
</table>
{% endblock %}

{% block js %}
    <script>
        console.log("index view")
    </script>
{% endblock %}

dashborad/templates/user/wuser.html
{% extends "public/layout.html" %}

{% block body %}
<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>userID</th>
        <th>username</th>
        <th>userGroup</th>
        <th>status</th>
        <th>phone</th>
        <th>职位</th>
        <th>Department</th>
        <th>email</th>
    </tr>

{% for i in page_obj.object_list %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ i.id }}</td>
    <td>{{ i.username }}</td>
    <td>
        {% for g in i.groups.all %}
        {{ g.name }}&#12288;
        {% endfor %}
    </td>
    <td class="user_status">
        {% if i.is_active %}
        <span class="glyphicon glyphicon-ok-circle text-success"></span>正常
        {% else %}
        <span class="glyphicon glyphicon-warning-sign text-warning"></span>禁止
        {% endif %}
    </td>
    <td>{{  i.profile.phone }}</td>
    <td>{{  i.profile.title }}</td>
    <td>{{  i.profile.department.name|default_if_none:'no department'}}</td>
    <td>{{ i.email }}</td>
    <td>
        <div class="btn-group">
            <div class="btn-group">
                <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="false">
                    修改
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                        <li role="presentation"><a role="menuitem" tabindex="-1" href="/user/modp/?user={{ i.id }}">部门</a></li>

                    <!--{% if perms.dashborad.change_department %}-->
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/user/modp/?user={{ i.id }}">部门</a></li>
                    <!--{% endif %}-->
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/user/mp/?user={{ i.id }}">手机号</a></li>
                            <!--<li role="presentation"><a role="menuitem" tabindex="-1" href="#" data='{"uid": "{{ user.id }}"}' class="user_to_group">Add Group</a></li>-->
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#" data='{"uid": "{{ i.id }}"}' class="user_to_group">添加指定组</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>
                </ul>
            </div>
            {% if i.is_active %}
                <button type="button" class="btn btn-sm btn-warning modify_user_status" status="true" data="{{ i.id }}"> disalbe</button>
            {% else %}
                <button type="button" class="btn btn-sm modify_user_status btn-info" status="false" data="{{ i.id }}">enable</button>
            {% endif %}
        </div>
            </td>
</tr>
{% endfor %}
</table>
    <div class="modal fade" id="user_to_group_modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 id="user_to_group_modal_title"></h4>
                </div>
                <div class="modal-body form-inline col-xs-6">
                    <select class="form-control" id="all_user_group">
                    </select>
                    <button class="btn btn-primary" id="user_to_group_btn">提交</button>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button" value="取消">
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block js%}
<script>
    function change_status(obj, status){
        if(status=='true'){
            obj.html(' <span class="glyphicon glyphicon-ok-circle text-success"></span>正常')
        }else{
            obj.html('<span class="glyphicon glyphicon-warning-sign text-warning"></span>禁止')
        }
    }

    function modify_status(user_id){
        console.log(user_id)
        $.post('/user/modify/', {'user_id': user_id}, function(res){
        console.log(res)
        if(res.status ==0){
        console.log(res)
        }else{
         swal({
            title: res.errmsg,
            type: "error",
            confirmButtonText: "知道了"
            });
        }
        })
    }
    $(function(){
    $('.modify_user_status').click(function(){
    var click_obj = $(this)
    var status = click_obj.attr('status')
    if (status == 'true'){
        console.log(status)
        click_obj.removeClass('btn-warning').addClass('btn-info').attr('status', 'false').text(' enable');
        }else{
        click_obj.removeClass('btn-info').addClass('btn-warning').attr('status', 'true').text('disalbe');
        }
    change_status(click_obj.parents('td').siblings('.user_status'), status)
    modify_status(click_obj.attr('data'))

    })
        /*
        将用户添加指定组
         */
        var uid;
        var user_to_group_modal= $('#user_to_group_modal')
        var all_user_group = $('#all_user_group')
        $('.user_to_group').click(function () {
            user_to_group_modal.modal('show')
            var data = JSON.parse($(this).attr('data'));
            console.log(data)
            uid = data.uid
            console.log(uid)
            $.get('/group',{ 'uid': uid }, function (res) {
                var html = '<option value="0">请选择用户</option>'
                $.each(res, function (n, obj) {
                    html+= '<option value="'+obj.pk+'">'+obj.fields.name+'</option>>'
                })
                all_user_group.html(html)
            })
            return false;
        })
        // 执行用户添加到用户组
        $('#user_to_group_btn').click(function () {
            user_to_group_modal.modal('hide')
            console.log(all_user_group.val())
            gid = all_user_group.val()
            var url = '/group/usergroup/';
            $.post(url,{'uid': uid, 'gid':gid }, function (res) {
                console.log(res)
                if (res.status == 0 ){
                            setTimeout(function () {
                                window.location.reload()
                            },10)
                    }else{
                        console.log(res.msg)
                        swal('操作失败', res.msg, 'error')
                    }
            })
        })
    })
</script>
{% endblock %}